---

- hosts: all
  become: true
  tasks:

  - name: install package apache
    yum:
      name: httpd
      state: latest
      

  - name: install apache php support
    yum:
      name: php
      state: latest
